### ISSUE TITLE
Temperature monitor

### ISSUE THREAD

**Issue by gabrielmcf** [fordsfords/blink#7]
Is that possible to add a temperature monitor, using the "axp209 --temperature" command? Something like "when temperature is over a limit it set a GPIO to high".

**Comment by fordsfords** [comment]
Good idea!  I'm pretty busy with real-life these days, it may take a little while.

**Comment by gabrielmcf** [comment]
Take your time! I will try to do it myself and pull request it here, but i might take even more time than you...

**Comment by fordsfords** [comment]
Done!  Let me know what you think.

**Comment by gabrielmcf** [comment]
You are a machine! It works like a charm! I've noticed you are using the i2ceget function and noticed it has a little differente from the axp290 response. The axp290 returns a lower temperature compared to the i2c, safer that way!

**Comment by fordsfords** [comment]
The axp209 command has a bug in it that causes it to return too-small values for all multi-byte readings, including temperature, voltage, and current.  The fix is easy, and I plan to issue a pull request to CHIP's repo this weekend to fix it.  (It's mentioned in the BBS.)  But of course that will only fix it in some future CHIPOS release; all existing CHIPsters will continue to have inaccurate results from axp209.

That's why I rolled my own, to fix the bug.  :-)
